name: Prevent Direct Main Push

on:
  push:
    branches: [main]

jobs:
  block-main-push:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        run: |
          echo "Push to main is not allowed. Please create a PR from a separate branch."
          exit 1